foodmaker/urls.py
from django.urls import include,path,re_path
from accounts import views as accounts_views
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',accounts_views.signup, name='signup'),
    path('signup/user', accounts_views.signup_user, name='signup_user'),
    path('signup/restaurant', accounts_views.signup_restaurant, name='signup_restaurant'),
    path('logout', auth_views.LogoutView.as_view(), name='signout'),
    path('',include('restaurant.urls')),
]

restaurant/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class restaurant(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='pictures', null=True, blank=True)
    city = models.CharField(max_length=500, null=True)
    address = models.TextField(null=True)
    tell = models.CharField(max_length=8, null=True)
    date_joined = models.DateField(auto_now_add=True)
    viwed_num = models.IntegerField(default=0)
    rate = models.FloatField(default=0.0)

    def __str__(self):
        return self.name


class menu(models.Model):
    restaurant = models.ForeignKey(restaurant, on_delete=models.CASCADE)


class food(models.Model):
    name = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to='pictures',null=True, blank=True)
    description = models.TextField(null=True)
    price = models.FloatField(default=0)
    ordered_num = models.IntegerField(default=0)
    rate = models.FloatField(default=0.0)
    menu = models.ForeignKey(menu, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.name


class ingredients(models.Model):
    name = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to='pictures',null=True, blank=True)
    description = models.TextField(null=True)
    price = models.FloatField(default=0)
    ordered_num = models.IntegerField(default=0)
    rate = models.FloatField(default=0.0)
    food = models.ForeignKey(food, on_delete=models.CASCADE,null=True)

templates/HomePage.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
    <link href="{% static 'Css/HomePage.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'Css/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    <script src="{% static 'Js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'Js/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'Js/js/bootstrap.js' %}"></script>
    <script src="{% static 'Js/restaurant_page.js' %}"></script>
    {#    <script src="{% static 'Js/js/j' %}"></script>#}
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body class="n_text">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler pl-0 ml-0" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand site_title ml-auto mr-0" href="{% url 'HomePage' %}">غذاساز</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {#            <li class="nav-item active">#}
            {#                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
            {#            </li>#}
            {% if user.username %}
                <a class="nav-link" href="#"> خوش آمدید{{ user.first_name }}{{ user.city }}</a>
                 <a class="nav-link" href="{% url 'signout' %}">خروج</a>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">ثبت نام کنید</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">وارد شوید</a>
            </li>
            {% endif %}
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">-->
        <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
        <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--</form>-->
    </div>
</nav>
{% block page %}
    <div class="container-fluid">
        <!--<div class="row">-->
        <div class="row mx-5 px-3">
            <div class="col-12">
                <h2 class="text-center title mt-lg-5">جست و جو</h2>
                <p class="text-center">میتونی اینجا محلی که هستی یا اسم رستورانی که میخوای رو سرچ کنی.</p>
                <form class="form">
                    <div class="form-row">
                        <div class="col-7">
                            <input type="text" class="form-control" placeholder="محله">
                        </div>
                        <div class="col-4">
                            <input type="text" class="form-control" placeholder="رستوران">
                        </div>
                        <div class="col-1">
                            <button type="button" class="btn bg-dark text-light my-2 my-sm-0">جست و جو</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        {% block result %}
            <div class="row mr-lg-5 pr-5">
                <h2 class="title mt-5 col-12" style="left:45%;">رستوران های پرطرفدار</h2>
                {#<div class="card-deck mt-4 mx-2 mb-lg-5">#}
                {% for r in restaurants %}
                    <div class="card col-2 mr-lg-3 mb-2">
                        <a class="card-link text-dark" href="{% url 'restaurnat_page' pk=r.pk name=r.name %}">
                            <div class="card-header bg-transparent mr-0 p-0 text-center">{{ r.name }}</div>
                            {% if r.image %}
                                <div class="card-img-top" style="background-image: {{ r.image }}">
                                    <p class="card-text text-center">{{ r.address }}</p>
                                </div>
                            {% else %}
                                <div class="card-img-top d-block"
                                     style="background-image: url(../static/picture/restaurant_default1.jpg)">
                                    <p class="card-text text-center">{{ r.address }}</p>
                                </div>
                            {% endif %}
                            <div class="card-footer p-0">
                                {% for i in "xxxxx" %}
                                    {% if forloop.counter <= r.rate %}
                                        <span class="fas fa-star fa-xs"></span>
                                    {% else %}
                                        <span class="far fa-star fa-xs"></span>
                                    {% endif %}
                                {% endfor %}

                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endblock %}
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close text-left" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Recipient:</label>
                            <input type="text" class="form-control" id="recipient-name">
                        </div>
                        <div class="form-group">
                            <label for="message-text" class="col-form-label">Message:</label>
                            <textarea class="form-control" id="message-text"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send message</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/ingredients_show.html
{#{% extends 'restaurant_page.html' %}#}

{#{% block modal %}#}
    <script src="../static/Js/restaurant_page.js"></script>
    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New message</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group">
                <label for="recipient-name" class="col-form-label">Recipient:</label>
                <input type="text" class="form-control" id="recipient-name">
              </div>
              <div class="form-group">
                <label for="message-text" class="col-form-label">Message:</label>
                <textarea class="form-control" id="message-text"></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Send message</button>
          </div>
        </div>
      </div>
    </div>
{#{% endblock %}#}

templates/restaurant_page.html
{% extends 'HomePage.html' %}
{% load templatetags %}

{% block title %}{{ restaurant.name }}{% endblock %}

{% block page %}
    <link href="../static/Css/restaurant_page.css" rel="stylesheet" type="text/css">
    <script src="../static/Js/restaurant_page.js"></script>
    <div class="container-fluid text-right">
        <div class="row mt-4 mx-4">
            <div class="card col-12">
                <div class="card-header">
                    {% if r.image %}
                        <img src="{{ restaurant.image }}" class="rounded-circle float-right">
                    {% else %}
                        <img src="../static/picture/restaurant_default1.jpg" class="rounded-circle float-right"
                             style="height: 140px; width: 140px">
                    {% endif %}
                    <p class="card-text float-right mt-5 mr-5">{{ restaurant.name }}</p>
                    <div class="float-left mt-5">
                        {% for i in "xxxxx" %}
                            {% if forloop.counter <= restaurant.rate %}
                                <span class="fas fa-star fa-xs"></span>
                            {% else %}
                                <span class="far fa-star fa-xs"></span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <br><br><br><span class="card-text float-right mr-4">آدرس: </span><span
                        class="card-text">{{ restaurant.address }}</span>
                    {#                                            <h5 class="card-title">Special title treatment</h5>#}
                    {#                        <a href="#" class="btn btn-primary">Go somewhere</a>#}
                </div>
            </div>
        <ul class="nav justify-content-end pr-0 nav-tabs mt-2 mb-0 col-12">
          <li class="nav-item">
            <a class="nav-link active title text-dark" href="#">منو</a>
          </li>
          <li class="nav-item">
            <a class="nav-link title text-dark" href="#">صورتحساب</a>
          </li>
        </ul>
            <div class="card col-12 mt-0 ml-5 float-right">
                {#                <div class="card-header"></div>#}
                <div class="card-body px-5">
                    <div class="row mr-5">
                        {% for f in foods %}
                            <div class="card col-2 mr-3 mt-3 border-secondary">
                                {#                                <a class="fa fa-pencil" data-toggle="modal" href="{% url 'item_edit' item.id %}"#}
                                {#                                   data-target="#modal{{ food.pk }}" title="edit item" data-tooltip></a>#}
                                {#                                href="{% url 'ingredient_show' foo=f %}"#}
                                <a class="card-link text-dark" data-toggle="modal" data-target="#Modal-{{ f.pk }}"
                                   data-whatever="@getbootstrap" onclick="{% define f.pk as key %}">
                                    <div class="card-header bg-transparent mr-0 p-0 text-center">{{ f.name }}</div>
                                    {% if f.image %}
                                        <img class="card-img-top" src="{{ f.image }}">
                                    {% else %}
                                        <img class="card-img-top d-block" src="../static/picture/food_default.jpg">
                                    {% endif %}
                                    <div class="card-footer p-0">
                                        <small class="text-muted text-left">{{ f.rate }}</small>
                                        <small class="text-muted text-right">{{ f.price }}</small>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}

                    </div>
                    {% block modal %}
                        {% for food in foods %}
                            <div class="modal fade" id="Modal-{{ food.pk }}" tabindex="-1" role="dialog"
                                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">مخلفات اضافی خود را انتخاب
                                                کنید</h5>
                                            <button type="button" class="close ml-0" data-dismiss="modal"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                {% for i in food.ingredients_set.all %}
                                                    <div class="col-3">
                                                        <a class="btn fas fa-plus fa-1x mr-4"></a>
                                                        <p class="bg-transparent text-center p-1 mt-1">
                                                            {{ i.name }}</p>
                                                        <a class="btn fas fa-minus fa-1x mr-4"></a><br>
                                                        {% for q in "xxx" %}
                                                            {% if forloop.counter <= i.rate %}
                                                                <span class="fas fa-star fa-xm text-right"></span>
                                                            {% else %}
                                                                <span class="far fa-star fa-sm text-right"></span>
                                                            {% endif %}
                                                        {% endfor %}
                                                    <small class="text-muted text-right mr-4">{{ i.price }}</small>
                                                        {#                                                        </a>#}
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary ml-2">Send message</button>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

<script>
    {% for food in foods %}
        {% for ingredient in food.ingredients_set.all %}
            $('#Modal-{{ food.pk }}').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget); // Button that triggered the modal
                var recipient = button.data('whatever');// Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this);
                modal.find('.modal-title').text('New message to ' + recipient);
                modal.find('.modal-body input').val(recipient)
            });



        {% endfor %}
    {% endfor %}

</script>

templates/signup.html
{% extends 'HomePage.html' %}
{% load templatetags %}

{% block title %}ثبت نام{% endblock %}

{% block page %}
    <div class="container text-right">
        <div class="row mt-4 mx-4">
            <div class="card col-12">
                <div class="card-header"></div>
                <div class="card-body text-center">
                    <h5 class="card-title">به عنوان چه کسی میخواهید ثبت نام کنید؟</h5>
{#                    <p class="card-text">}</p>#}
                    <a href="{% url 'signup_restaurant' %}" class="btn btn-dark">رستوران</a>
                    <a href="{% url 'signup_user' %}" class="btn btn-dark">کاربر</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/signup_form.html
{% extends 'HomePage.html' %}

{% block page %}
    <div class="row my-5 mx-5">
    <div class="col-9" style="margin-right: 12%;">
    <div class="card text-right">
        <div class="card-header bg-dark text-light">
            <h3 class="title" style="font-size: 22px!important;">فرم ثبت نام {{ type }}</h3>
        </div>
        <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <button type="submit" class="btn btn-primary">Create an account</button>
        </form>
        </div>
      </div>
    </div>
    </div>
    </div>
{% endblock %}